# Generated by Django 3.2.8 on 2021-12-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTour',
        ),
    ]
