# Generated by Django 3.2.8 on 2021-12-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_ordertour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
